# Generated by Django 4.2.8 on 2023-12-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/images/', verbose_name='Gallery'),
        ),
    ]
