# Generated by Django 4.2.8 on 2024-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_gallery_options_alter_gallery_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=155)),
                ("last_name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=123)),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
    ]
